# Repository configuration for GitHub statistics collection
# Add new repositories here organized by technology category

repositories:
  AI/ML:
    # Top AI/ML Repositories - Comprehensive List
    - tensorflow/tensorflow                   # 191k stars - Google's ML framework
    - pytorch/pytorch                        # 92k stars - Facebook's ML framework
    - huggingface/transformers               # 146k stars - State-of-the-art NLP models
    - scikit-learn/scikit-learn              # 63k stars - Classical ML
    - ollama/ollama                          # 146k stars - Run LLMs locally
    - microsoft/ML-For-Beginners             # 69k stars - ML course by Microsoft
    - facebookresearch/detectron2            # 30k stars - Object detection platform
    - openai/whisper                         # 70k stars - Speech recognition
    - CompVis/stable-diffusion               # 68k stars - Text-to-image generation
    - ageitgey/face_recognition              # 53k stars - Face recognition library
    - keras-team/keras                       # 62k stars - High-level neural networks API
    - deepfakes/faceswap                     # 52k stars - Deepfakes software
    - fastai/fastai                          # 26k stars - Deep learning library
    - facebookresearch/faiss                 # 31k stars - Similarity search library
    - microsoft/DeepSpeed                    # 35k stars - Deep learning optimization
    - ray-project/ray                        # 33k stars - Distributed computing
    - dmlc/xgboost                           # 26k stars - Gradient boosting
    - streamlit/streamlit                    # 35k stars - ML app framework
    - gradio-app/gradio                      # 33k stars - ML model interfaces
    - explosion/spaCy                        # 30k stars - Industrial NLP

  TypeScript:
    - nestjs/nest
    - prisma/prisma
    - adonisjs/core
    - typeorm/typeorm
    - sequelize/sequelize
    - trpc/trpc
    - fastify/fastify
    - taskforcesh/bullmq
    - mikro-orm/mikro-orm
    - drizzle-team/drizzle-orm
    - kysely-org/kysely
    - colinhacks/zod
    - winstonjs/winston
    - pinojs/pino
    - helmetjs/helmet
    - moleculerjs/moleculer
    - typestack/routing-controllers
    - lukeautry/tsoa
    - tsedio/tsed
    - lobehub/lobe-chat
    - vercel/ai

  "C# ASP.NET":
    - dotnet/aspnetcore
    - aspnetrun/run-aspnetcore-microservices
    - DapperLib/Dapper
    - jasontaylordev/CleanArchitecture
    - dotnet/efcore
    - App-vNext/Polly
    - dotnet/orleans
    - HangfireIO/Hangfire
    - nopSolutions/nopCommerce
    - ThreeMammals/Ocelot
    - OrchardCMS/OrchardCore
    - dotnetcore/CAP
    - gothinkster/aspnetcore-realworld-example-app

  Developer_Tools:
    - karpathy/nn-zero-to-hero

  # Future categories to expand research:
  # B2B_Solutions:
  #   - example/repo
  # 
  # Frontend_Frameworks:
  #   - example/repo
  # 
  # Backend_Infrastructure:
  #   - example/repo